spring.application.name=learn
server.port=8001
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

com.king.name=king
com.king.age=30
com.king.birthday=1990-01-01
com.king.boss=true